### ISSUE TITLE
Does this support dataset?

### ISSUE THREAD

**Issue by ruoyuwangeel4930** [chrdiller/KinectFusionLib#1]
Hi chrdiller,

Does this code support a pre-recorded dataset or only a living Kinect camera stream?

Thank you!

**Comment by chrdiller** [comment]
Hi,

it definitely does! Have a look at [KinectFusionApp](https://github.com/chrdiller/KinectFusionApp), there I implemented a camera using a prerecorded sequence (with sensor data stored as individual png files). If you have a specific format you can also easily implement that by overriding the DepthCamera get_parameters and grab_frame member functions.
KinectFusionLib itself just takes an OpenCV Mat<float> as depth map and a Mat<Vec3b> as color map.

Best,
Christian
