### ISSUE TITLE
How to initialize the class kinectfusion::Pipeline

### ISSUE THREAD

**Issue by hoangcuongbk80** [chrdiller/KinectFusionLib#7]
Hi,

I am getting a error when executing the code as following:

```
kinectfusion::GlobalConfiguration configuration;
kinectfusion::CameraParameters mycamera;
......(code for providing parameters for mycamera).......
kinectfusion::Pipeline pipeline { mycamera, configuration };
```

![error](https://user-images.githubusercontent.com/10355081/43130071-14cefa90-8f36-11e8-8e0f-0a90c60b4fa4.png)

Any suggestion? Thanks for your time!

**Comment by chrdiller** [comment]
Hi,

this looks like a linker error rather than an error in the pipeline initialization. 
Seems like some parts of libkinectfusion are not found but also the CUDA module of OpenCV. 
Did you install all libraries correctly?

**Comment by hoangcuongbk80** [comment]
Thanks! I reinstall OpenCV with CUDA and it works now.
